apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: geonodes
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geonodes
      type: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: geonodes
        type: web
    spec:
      containers:
        - name: web
          image: fstanczyk/geonodes.io:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: geonodes
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geonodes
      type: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: backend
        app: geonodes
        type: api
    spec:
      containers:
        - name: api
          image: fstanczyk/geonodes-web:latest
          env:
            - name: WSS_INFURA_MAINNET_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: WSS_INFURA_MAINNET_API_KEY
            - name: WSS_INFURA_GOERLI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: WSS_INFURA_GOERLI_API_KEY
            - name: WSS_MAINNET_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: WSS_MAINNET_PRIVATE_KEY
            - name: WSS_MAINNET_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: WSS_MAINNET_PUBLIC_KEY
            - name: WSS_GOERLI_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: WSS_GOERLI_PRIVATE_KEY
            - name: WSS_GOERLI_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: WSS_GOERLI_PUBLIC_KEY
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8001
