apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: geonodes
    type: web

---

apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: ClusterIP
  ports:
  - port: 8001
    name: http
    protocol: TCP
  selector:
    app: geonodes
    tier: backend
    type: api